baseURL = "https://marzukia.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 2

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.article]
  showComments = true

[services]
  [services.x]
    disableInlineCSS = true

  [services.googleAnalytics]
    id = 'G-F52W3SZVZ4'

[params]
  [params.githubPages]
    enabled = true

[params.comments]
  enable = true
  provider = "isso"
  [params.comments.isso]
    address = "https://comments.junkyard.sh"
