canonifyurls = true
summaryLength = 30
enableEmoji = true

publishDir = "marzukia.github.io"

googleAnalytics = "UA-170171726-1"

baseURL = "https://marzukia.github.io"
title = "Andryo Marzuki"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true

[params]
  description = "Personal dev blog of Andryo Marzuki"
  copyright = "© 2020, Andryo Marzuki"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"


[markup]
  [markup.highlight]
    style = "monokai"
    tabWidth = 4

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
