canonifyurls = true
summaryLength = 30
enableEmoji = true
staticDir = ['static']

publishDir = "marzukia.github.io"

googleAnalytics = "UA-170171726-1"

baseURL = "https://marzukia.github.io"
title = "Andryo Marzuki"
theme = "salt"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true

[params]
  description = "Personal dev blog of Andryo Marzuki"
  copyright = "© 2020, Andryo Marzuki"
  dark = "auto"
  highlight = true

    [params.socials]
        instagram = "https://instagram.com/andryo"
        github = "https://github.com/marzukia"
        linkedin = "https://linkedin.com/in/andryomarzuki"

[permalinks]
  posts = "post/:title/"


[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 4

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
